spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_food_delivery
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

